### PR TITLE
Add elasticsearch 5 support

### PR DESCRIPTION
**Pull request by mamedin**
This change includes the configuration changes described in issue #7 when using Elasticsearch version 5.0 or greater for files:

- /etc/default/elasticsearch
- /etc/elasticsearch/elasticsearch.ym

### CODE REVIEW

**Comment by hakamine** [comment]
In the past I also thought that using the official ES role should deprecate use of our role, but after using it for some time, it looks to me that it does a little too much and doesn't fit our use cases too well (the official role seems to be more appropriate for clusters, it also has some "unexpected" default values for directory locations and the service name). I would say that it still makes sense to update our role (trying to keep it as simple as possible). What does everybody think?

**Comment by scollazo** [comment]
@hakamine I'm ok with using our custom role, but if we follow that path, we need to add support for centos to it.

**Comment by scollazo** [comment]
I used this role to install ES 6.5.4 (needed by Archivematica 1.9.x) , this was in my vars file:

```
elasticsearch_version: "6.5.4"
elasticsearch_download_url: "https://artifacts.elastic.co/downloads/elasticsearch/"
```

Not sure if the url change is also needed for 5.x. Other than that, we should merge this, #15 and the other pending pr's, and start using our own role for all elasticsearch deployments

**Comment by mamedin** [comment]
This PR has been replaced by https://github.com/artefactual-labs/ansible-elasticsearch/pull/16

**Pull request closed without merging**
